### ISSUE TITLE
UI shows no data except for stats

### ISSUE THREAD

**Issue by edmz** [akira/exq_ui#17]
I am using exq_ui along phoenix. The workers are doing their thing and if I go to exq_ui i see the stats getting updated (16 processed, 13 failed, etc).

The names of the queues are also listed.

But  I can't see any, for example, the failures. The failures table is empty even though the stats say that '13 failed'.

Any ideas on what to check?

Thanks in advance.

**Comment by akira** [comment]
@edmz Do you see the failures in the "retries" queue?  Note that they go in the retry queue first, the failure table is only when max retries have been reached. If they're not showing up anywhere, then I'd need to take a look.

**Comment by akira** [comment]
@edmz I've updated Exq and ExqUI, I think the retries / scheduled queue should work. I think there was an issue with Timex that may have been causing it, let me know if it works with latest version (0.7.0).

**Comment by migore** [comment]
I'm using version 0.7.0 and the issue still persist for Failed, just show the number but the list doesn't show any entry.

**Comment by vrosancic** [comment]
Hi, is there any update here? I am also seeing just seeing the number of failed jobs. It would be useful to see failure messages. See screenshot.
![screen shot 2016-12-20 at 09 16 42](https://cloud.githubusercontent.com/assets/8770941/21343041/3378a56a-c695-11e6-9b1c-57a5d12b8222.png)

**Comment by akira** [comment]
After looking at this, I'm suspecting that there's a misunderstanding here, caused by the way the UI displays the "Failed Counter" counter and "Failed list". The "Failed counter" increments every time something fails, even if it goes back to the "Retry" queue. The "Failed list" only displays items that have exhausted their retries. So while the "Failed counter" can be 4, the "Failed List" could be 0 if the jobs went back to retry.

Here is screenshot:

<img width="1203" alt="screen shot 2016-12-24 at 4 05 22 pm" src="https://cloud.githubusercontent.com/assets/43946/21468761/81012d28-c9f3-11e6-9f2f-a88fcc211594.png">

I think I'm going to separate the "Retry" from "Dead" like Sidekiq does. So there will be a "Retry" that is a counter only, and then a "Dead" counter that links to a list.

**Comment by akira** [comment]
See #33 (in master), separate Fail into a separate list.

**Comment by akira** [comment]
Published 0.8.3 with this fix

**Comment by vrosancic** [comment]
Hi @akira, thanks for this improvement. I think it is better, but still not totally clear:

1. In my opinion, there is no need for 'Failed Counter'. It only confuses me because some of those jobs failed totally (and they are dead now), and some of them succeeded after retries. If you need to see how many jobs failed in retrying, you can go in 'Retry list' and check how many retries there are. And you have 'Dead jobs list' for jobs that failed totally.

2. It would be ok to see an error in 'Retry list'. Without error, I don't know why something failed until it becomes dead. 

3. In 'Dead jobs list', I don't see the whole error (see screenshot). I can scroll to see it, but it would be better to have some line break inside the cell.

 ![exq_ui_failures](https://cloud.githubusercontent.com/assets/8770941/21585889/319cba54-d0c9-11e6-8042-2b974361c477.png)

**Comment by vrosancic** [comment]
@akira, if you agree with above suggestions, I can try to implement them and create pull request.

**Comment by akira** [comment]
@vrosancic thanks for the suggestions. 

1. I would prefer to keep this counter, as it still shows how many failures occurred and it's also consistent with Sidekiq

2. Good suggestion, agreed. 

3. Perhaps we can have a modal popup that displays all the details, along with the full error?
